# Generated by Django 2.2.6 on 2020-01-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': 'choices'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quiz'},
        ),
    ]
