# Generated by Django 2.2.6 on 2020-01-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200129_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='incorrect_answers',
        ),
        migrations.AddField(
            model_name='questions',
            name='incorrect_answer_1',
            field=models.CharField(default='no', max_length=400),
        ),
        migrations.AddField(
            model_name='questions',
            name='incorrect_answer_2',
            field=models.CharField(default='no', max_length=400),
        ),
        migrations.AddField(
            model_name='questions',
            name='incorrect_answer_3',
            field=models.CharField(default='no', max_length=400),
        ),
        migrations.AddField(
            model_name='questions',
            name='incorrect_answer_4',
            field=models.CharField(default='no', max_length=400),
        ),
    ]
