# Generated by Django 2.2.6 on 2020-01-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200129_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='incorrect_answer_1',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='questions',
            name='incorrect_answer_2',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='questions',
            name='incorrect_answer_3',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='questions',
            name='incorrect_answer_4',
            field=models.CharField(default='', max_length=400),
        ),
    ]
