# Generated by Django 2.2.6 on 2020-02-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200129_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
