# Generated by Django 2.2.6 on 2020-02-12 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_choice_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='incorrect_answers',
            new_name='user_answer',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='correct',
        ),
    ]
