# Generated by Django 2.2.6 on 2020-02-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200213_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='weighting',
            field=models.IntegerField(default=1),
        ),
    ]
