# Generated by Django 3.0.3 on 2020-02-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_questions_weighting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='score',
            field=models.CharField(max_length=25),
        ),
    ]
