# Generated by Django 3.0.3 on 2020-03-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('Computing', 'Computing'), ('English', 'English'), ('Geography', 'Geography'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Music', 'Music'), ('Art', 'Art'), ('History', 'History')], default='Computing', max_length=15),
        ),
    ]
