# Generated by Django 3.0.3 on 2020-03-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='additional_content_1',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='additional_content_2',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
    ]
