# Generated by Django 3.0.3 on 2020-03-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200322_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': 'Lesson'},
        ),
    ]
