# Generated by Django 3.0.3 on 2020-03-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200322_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file_upload_1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='file_upload_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='file_upload_3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
